import Head from "next/head";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import requests from "../utils/requests";
export default function Home({ results }) {
  console.log(results);
  return (
    <div>
      <Head>
        <title>Movie App v3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}

      <Header />

      {/* Nav */}

      <Nav />

      {/* Results */}

      <Results results={results} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const ganre = context.query.ganre || "fetchTrending";
  const request = await fetch(
    `https://api.themoviedb.org/3${requests[ganre]?.url}`
  ).then((res) => res.json());

  return {
    props: {
      results: request.results,
    },
  };
}
